package-lock.json
package.json
src/components/Carousel/Bullets.tsx
src/components/Carousel/index.tsx

enhancement #435 - [Carousel]: Add left and right arrows

---

src/__snapshots__/storybook.test.ts.snap
src/components/Icon/index.tsx
src/components/Table/fixtures/7_sample_data.ts
src/components/Table/utils.tsx

enhancement #440 - Default to altText when icon link is broken

---

package.json
src/components/Filters/FiltersSummary.tsx
src/components/Tabs/Tab.tsx
src/components/Tabs/TabPane.tsx
src/components/Tabs/index.tsx

feat #443 - Tab enhancements for context hub

---

src/components/Icon/index.tsx
src/components/Table/IconCell.tsx

fix #448 - Fix icon error handling for icon with label

---

src/components/Icon/index.tsx

fix #448 - Fix icon error handling

---

package.json
src/__snapshots__/storybook.test.ts.snap
src/components/Button/Button.stories.tsx
src/components/Button/index.tsx
src/components/Button/utils.ts

feat #452 - Allow button color to be customized

---

package.json
src/components/Button/utils.ts

fix #455 - Fix hover styles on customized color button

---

package.json
src/components/Code/index.tsx

chore #466 - [Code] Expose onLoad prop for AceEditor

---

src/components/Code/index.tsx

fix #468 - Code: copy bug

---

package.json
src/components/Code/index.tsx
src/components/Tabs/index.tsx

enhancement #471 - [Tabs] Expose onTabChange method

---

package.json
src/components/Code/utils.ts

fix #478 - [Code] Update highlight color

---

src/components/NotificationV2/Notification.tsx
src/components/NotificationV2/utils.ts

enhancement #484 - Allow ReactNode to be passed as message

---

package.json
src/components/NotificationV2/NotificationV2.stories.tsx
src/components/NotificationV2/utils.ts

enhancement #490 - [Notifications] Standalone mode

---

package.json
src/components/CodeDiffViewer/styles.ts

fix #500 - [Code Diff Viewer] Add word break for string

---

package.json
src/components/InfoTip/index.tsx

fix #504 - Make InfoTip tooltip config props optional

---

package.json
src/components/Accordion/Animate.tsx

chore #519 - Expose duration as prop for animate

---

.github/workflows/npm-publish.yml
package.json

chore #527 - Bump node version on publish gh action

---

.eslintrc.js
.github/workflows/codegen.yml
codegen.js
package-lock.json
package.json
src/components/Form/Form.stories.tsx
src/components/Form/FormCheckbox/FormCheckbox.test.tsx
src/components/Form/FormCheckbox/index.tsx
src/components/Form/index.tsx

feat #529 - Form checkbox

---

package.json
src/__snapshots__/storybook.test.ts.snap
src/components/Form/FormCheckbox/index.tsx
src/components/Form/FormSubmitButton/index.tsx
src/components/Form/index.tsx
src/components/Tooltip/utils.ts
src/components/Wizard/index.tsx

enhancement #531 - Form & Wizard Improvements

---

.storybook/manager.js
package.json
src/components/Code/index.tsx
src/components/Form/FieldContext.ts
src/components/Form/Form.stories.tsx
src/components/Form/FormCheckbox/FormCheckbox.test.tsx
src/components/Form/FormCheckbox/index.tsx
src/components/Form/FormChipInput/index.tsx
src/components/Form/FormCode/index.tsx
src/components/Form/FormInput/FormInput.test.tsx
src/components/Form/FormInput/index.tsx
src/components/Form/FormMultiSelect/index.tsx
src/components/Form/FormRadioGroup/FormRadioGroup.test.tsx
src/components/Form/FormSelect/FormSelect.test.tsx
src/components/Form/FormSelect/index.tsx
src/components/Form/FormSubmitButton/FormSubmitButton.test.tsx
src/components/Form/FormSubmitButton/index.tsx
src/components/Form/FormTimeInput/index.tsx
src/components/Form/FormTimezone/index.tsx
src/components/Form/FormToggle/FormToggle.test.tsx
src/components/Form/FormToggle/index.tsx
src/components/Form/FormTree/FormTree.test.tsx
src/components/Form/FormTree/index.tsx
src/components/Form/index.tsx
src/components/Table/Table.stories.mdx

enhancement #533 - [Form] Code component

---

package-lock.json
package.json
src/__snapshots__/storybook.test.ts.snap
src/components/JSONPathPicker/index.tsx
src/components/JSONPathPicker/styles.ts
src/components/JSONPathPicker/utils.tsx

enhancement #535 - [JSONPathPIcker] Read only mode

---

package.json
src/components/NotificationV2/index.tsx

fix #537 - [Notification] Increase z-index so it shows over modals

---

package.json
src/components/Form/index.tsx

fix #547 - Remove keydown handler for form

---

package-lock.json
package.json
src/components/Banner/index.tsx

enhancement #549 - Add prop to persist banner state

---

package-lock.json
package.json
src/components/Code/utils.ts
src/components/Input/utils.ts
src/components/Table/styles.ts

Closes #555 
Closes #556 
Closes #557

fix #555, #556, #557 - Batch Fixes

---

package-lock.json
package.json
src/__snapshots__/storybook.test.ts.snap
src/components/Avatar/index.tsx
src/components/Code/index.tsx
src/components/Table/index.tsx

fix #561 - [Avatar] Fix styles in dark mode
enhancement #562 - [Code] Add code controls classes props
enhancement #563 - [Table] Add controls boolean prop to determine controls visibility
Closes #561
Closes #562 
Closes #563

fix #561, enhancement #562, #563 - Batch improvements & fixes

---

package-lock.json
package.json
src/__snapshots__/storybook.test.ts.snap
src/components/Table/TableSkeleton.tsx
src/components/Table/index.tsx
src/components/Table/styles.ts
src/components/Table/types.ts

Closes #565 and `web-query-builder` [#31](https://github.com/dassana-io/web-query-builder/issues/31) 
Updates the Table component header color and allows Table styles to be overwritten

enhancement #565 - Table header color blends in with background in dark mode

---

package.json
src/components/Table/CellWithTooltip.tsx
src/components/Table/types.ts
src/components/Table/utils.tsx
src/components/TableDrawer/TableDrawer.tsx

fix #567 - [Table] Add functionality to show booelans as strings
fix #568 - [TableDrawer] Fix table loader visiblity
Closes #567
Closes #568

fix #567, #568 - Table fixes

---

package.json
src/components/Table/TableSkeleton.tsx

fix #571 - [TableSkeleton] Keep table cell skeleton width consistent between rerenders

---

package.json
src/components/utils.ts

fix #575 - [Table] Fix cell data not loading for keys with double quotes and spaces

---

package-lock.json
package.json
src/components/Table/types.ts
src/components/Table/utils.tsx
src/components/utils.ts

fix #575 - Add key formatter for columns

---

package-lock.json
package.json
src/components/Filters/FilterUnit/ValuesMultiSelect/utils.ts
src/components/Form/FormTimezone/index.tsx
src/components/Select/BaseSelect.tsx
src/components/Select/MultiSelect/index.tsx
src/components/Select/MultiSelect/utils.ts
src/components/Select/SingleSelect/types.ts
src/components/Timezone/index.tsx
src/components/Timezone/types.ts

enhancement #573 - Start using profile v2 APIs in the FTU flow

---

package-lock.json
package.json
src/components/MultipleChoice/BaseMultipleChoice.tsx
src/components/MultipleChoice/MultipleChoiceItem.tsx
src/components/MultipleChoice/types.ts

Change progression shortcut for role selection

---

package-lock.json
package.json
src/__snapshots__/storybook.test.ts.snap
src/components/Table/__tests__/utils.test.tsx
src/components/Table/index.tsx
src/components/Table/styles.ts
src/components/Table/utils.tsx

fix #582 - [Table] Fix disabled row click color

---

package.json
src/components/Code/utils.ts
src/components/Table/EditableCell.tsx
src/components/Table/Table.stories.tsx
src/components/Table/__tests__/utils.test.tsx
src/components/Table/index.tsx
src/components/Table/types.ts
src/components/Table/utils.tsx
src/components/TableDrawer/TableDrawer.tsx
src/components/TableDrawer/index.tsx

enhancement #584 - [Table]: Allow id to be optional parameter in data
enhancement #585 - [Code]: Update light mode background color
Closes #584 
Closes #585

enhancement #584, #585 - Table & Code updates

---

package.json
src/components/Banner/index.tsx
src/components/Code/index.tsx

enhancement #587 - [Banner]: Add titleClasses prop
enhancement #588 - [Code]: Expose hightlightActiveLine prop
Closes #587
Closes #588

enhancement #587, #588 - Enhancements for Sample App

---

package-lock.json
package.json
src/components/RadioButtonGroup/utils.ts

enhancement #590 - RadioGroupButton light theme colors

---

package.json
src/components/ProgressBar/index.tsx

enhancement #592 - Progressbar classes prop should be optional

---

package-lock.json
package.json
src/components/Pages/Error404.tsx

enhancement #594 - Allow hiding of Error404 button

---

package.json
src/components/Table/TableSkeleton.tsx

fix #596 - Fix table skeleton loader not being properly memo-ized

---

package.json
src/components/Table/types.ts
src/components/Table/utils.tsx

enhancement #601 - [Table] Add prop for date formatter

---

package.json
src/components/Link/utils.ts
src/components/Markdown/index.tsx

fix #604 - [Markdown] Fix broken styles

---

package-lock.json
package.json
src/components/IconButton/utils.ts

Disabled IconButton should maintain same border color on hover

---

package.json
src/components/Banner/index.tsx
src/components/Markdown/index.tsx
src/components/Markdown/styles.ts

fix #604 - Update markdown styles

---

package-lock.json
package.json
src/components/Tooltip/utils.ts

enhancement #610 - Fix tooltip arrow background color

---

package.json
src/components/Paginate/index.tsx
src/components/Tabs/TabPane.tsx
src/components/Tabs/index.tsx

enhancement #612 - [Tabs] Add prop to control transition duration

---

package.json
src/components/Tabs/index.tsx

enhancement #614 - [Tabs] Expose tabConfg in tabsRef

---

package.json
src/components/QueryDisplay/index.tsx

enhancement #616 - [QueryDisplay] Add loading prop

---

package.json
src/components/QueryDisplay/index.tsx

enhancement #618 - [Query Builder] Allow ReactNode to be passed for name

---

package-lock.json
package.json
src/components/Timezone/index.tsx

enhancement #620 - Default timezone value

---

package-lock.json
package.json
src/components/Markdown/index.tsx

enhancement #622 - Link target in Markdown

---

package.json
src/components/QueryDisplay/index.tsx

enhancement #624 - [Query Display]: Add prop for name container classes

---

package.json
src/components/EditableField/index.tsx
src/components/QueryDisplay/index.tsx

enhancement #626 - [Query Display] Allow expandable to be configured by a prop

---

package.json
src/components/Toggle/utils.ts

enhancement #628 - [Toggle] Update active color

---

package-lock.json
package.json
src/__snapshots__/storybook.test.ts.snap
src/components/Link/index.tsx
src/components/Link/utils.ts

fix #630 - Link underline inconsistent between themes

---

package.json
src/components/EditableField/index.tsx

enhancement #634 - [EditableField] Add unsaved value styles

---

package-lock.json
src/components/QueryDisplay/index.tsx

fix #632 - Fix QueryDisplay component opening duplicate tabs

---

package-lock.json
package.json
src/components/Tabs/index.tsx

enhancement #638 - [Tabs] Expose activeIndex in tabs ref

---

package.json
src/components/EditableField/index.tsx
src/components/ShortcutMicrocopy/index.tsx
src/components/ShortcutMicrocopy/types.ts

enhancement #640, fix #641 - EditableField and ShortcutMicrocopy Updates

---

package-lock.json
package.json
src/components/Code/index.tsx

enhancement #643 - Code editor should allow `minLines`

---

package.json
src/components/EditableField/index.tsx
src/components/Input/index.tsx

enhancement #645 - [EditableField] Add ability to auto select on focus

---

package-lock.json
package.json
src/components/Markdown/Markdown.stories.tsx
src/components/Markdown/index.tsx

fix #648 - Links not getting underlined in markdown

---

package.json
src/components/IconButton/index.tsx
src/components/QueryDisplay/index.tsx

Add prop to pass class
Allow search icon to be hidden
Closes #654

enhancement #654 - [Query Display] Header enhancements

---

package-lock.json
package.json
src/components/ChipInput/index.tsx

fix #656 - Fix chip input values not showing up as tags

---

package-lock.json
package.json
src/components/Form/index.tsx
src/components/IconButton/index.tsx
src/components/Table/types.ts
src/components/Table/utils.tsx

Closes #658 
Closes #659 
Closes #660

enhancement #658, #660, fix #659 - Enhancements and fixes for notification rules

---

package-lock.json
package.json
src/__snapshots__/storybook.test.ts.snap
src/components/Paginate/index.tsx
src/components/Table/utils.tsx

fix #662 - [Table] Fix column sort for tag arrays
enhancement #663 - [Paginate] Add loading state
Closes #662 
Closes #663

fix #662, enhancement #663 - Search V3 Fixes

---

package-lock.json
package.json
src/components/Paginate/index.tsx

fix #671 - [Paginate] Reset to first page on page size change or if data length changes

---

package-lock.json
package.json
src/components/Select/MultiSelect/index.tsx

fix #673 - MultiSelect search should match everything

---

package-lock.json
package.json
src/components/ChipInput/index.tsx
src/components/ChipInput/utils.ts

enhancement #675 - Render tags full width

---

package-lock.json
package.json
src/components/Select/MultiSelect/index.tsx
src/components/Select/MultiSelect/types.ts

enhancement #679 - Allow unsorted multiselect options

---

package-lock.json
package.json
src/components/Form/FormToggle/index.tsx
src/components/Form/types.ts

enhancement #682 - Allow FormToggle to ignore form disabled state

---

package-lock.json
package.json
src/components/Form/FormTagsSelect/index.tsx
src/components/Form/index.tsx
src/components/Select/BaseSelect.tsx
src/components/Select/MultiSelect/styles.ts
src/components/Select/TagsSelect/TagsSelect.stories.tsx
src/components/Select/TagsSelect/index.tsx
src/components/Select/TagsSelect/types.ts

enhancement #684 - [Select] Tags Mode

---

package-lock.json
package.json
src/components/QueryDisplay/index.tsx

enhancement #681 - Query display component show action icons on hover

---

package-lock.json
package.json

chore #681 - v0.12.78 -> v0.12.79

---

package-lock.json
package.json
src/components/Select/index.ts

fix #693 - Export tags select

---

.github/workflows/chromatic.yml
package-lock.json
package.json
src/components/Select/SingleSelect/types.ts

enhancement #696 - Select component placeholder prop type

---

package-lock.json
package.json
src/components/Input/utils.ts

fix #701 - [Input] Fix unreadable text color on safari

---

package-lock.json
package.json
src/components/Form/FormToggle/index.tsx

enhancement #708 - Add containerClasses to FormToggle

---

package-lock.json
package.json
src/components/Tabs/Tabs.stories.tsx
src/components/Tabs/index.tsx

enhancement #710 - Split Tabs left and right

---

package-lock.json
package.json
src/components/Table/index.tsx
src/components/Table/styles.ts
src/components/Table/utils.tsx

enhancement #714 - [Table] Selectable Rows

---

package-lock.json
package.json
src/components/Checkbox/utils.ts
src/components/Table/styles.ts

fix #716 - [Table] Fix checkbox colors

---

package-lock.json
package.json
src/components/Form/FieldLabel/index.tsx
src/components/Form/types.ts

enhancement #719 - FormInput label should accept ReactNode

---

package-lock.json
package.json
src/components/Form/FormSelect/index.tsx
src/components/Form/types.ts
src/components/Table/EditableCell.tsx
src/components/Table/index.tsx
src/components/Table/types.ts
src/components/Table/utils.tsx
src/components/assets/styles/styleguide.ts

enhancement #724 - [Table] Add ability to pass ReactNode for select option for in row editing

---

package-lock.json
package.json
src/components/Filters/BaseFilters.tsx
src/components/Filters/FilterPopover.tsx
src/components/Filters/FilterUnit/ValuesInput/index.tsx
src/components/Filters/FilterUnit/ValuesInput/types.ts
src/components/Filters/FilterUnit/ValuesMultiSelect/ServerSide.tsx
src/components/Filters/FilterUnit/index.tsx
src/components/Filters/Filters.stories.tsx
src/components/Filters/FiltersContext.ts
src/components/Filters/ServerSideFilters/index.tsx
src/components/Filters/ServerSideFilters/utils.ts
src/components/Filters/fixtures/0_sample_data.ts
src/components/Filters/types.ts
src/components/Filters/utils.ts
src/components/Form/FormInput/index.tsx
src/components/Select/MultiSelect/index.tsx

enhancement #723, #726 - Changes to Filter V1 for dashboard and findings 

---

package-lock.json
package.json
src/components/Filters/ServerSideFilters/index.tsx

fix #728 - [Filters V1] Fix infinite loop in server side filters

---

package-lock.json
package.json
src/components/assets/styles/colors.ts

enhancement #730 - Add more colors

---

package-lock.json
package.json
src/components/Filters/FilterUnit/ValuesMultiSelect/ServerSide.tsx
src/components/Filters/ServerSideFilters/utils.ts
src/components/Select/MultiSelect/index.tsx
src/components/Select/MultiSelect/types.ts

fix #733 - [Filters] Clear options between filters 

---

package-lock.json
package.json
src/components/Filters/FilterUnit/ValuesMultiSelect/ServerSide.tsx

fix #735 - [Filters V1] Fix server side options not populating on first load

---

package-lock.json
package.json
src/__snapshots__/storybook.test.ts.snap
src/components/ProgressBar/index.tsx

feat #737 - Updated progress bar component

---

package-lock.json
package.json
src/components/Filters/BaseFilters.tsx
src/components/Filters/FiltersContext.ts
src/components/Filters/types.ts

enhancement #739 - [Filters] Add clear filters callback

---

package-lock.json
package.json
src/components/Filters/FilterUnit/index.tsx
src/components/Filters/styles.ts

enhancement #742 - [Filters] Remove operator and fix key disable

---

package-lock.json
package.json
src/components/Table/types.ts
src/components/Table/utils.tsx

chore #745 - Table type updates

---

package-lock.json
package.json
src/__snapshots__/storybook.test.ts.snap
src/components/Table/index.tsx
src/components/Table/styles.ts

enhancement #747 - Show additional info underneath table

---

package-lock.json
package.json
src/components/SplitPane/index.tsx

fix #749 - [Split Pane] Disable text highlighting when resizing

---

package-lock.json
package.json
src/components/Table/index.tsx

enhancement #751 - Table additionalInfo prop should accept ReactNode

---

package-lock.json
package.json
src/components/RiskIndicator/index.tsx
src/components/Table/types.ts

bugfix #753 - Critical should be purple

---

package-lock.json
package.json
src/components/Select/BaseSelect.tsx

enhancement #755 - Allow command-all text selection BaseSelect

---

package-lock.json
package.json
src/components/Filters/ServerSideFilters/index.tsx
src/components/Filters/ServerSideFilters/utils.ts

fix #757 - [Filters] onFilterSuggest is called with stale data

---

package-lock.json
package.json
src/components/Banner/Banner.stories.tsx
src/components/Banner/index.tsx
src/components/Banner/utils.ts
src/components/Select/BaseSelect.tsx

enhancement #759 - [Banner] Update banner for use with preferences

---

package-lock.json
package.json
src/components/SplitPane/index.tsx

enhancement #761 - [SplitPane] Migrate save settings from local storage to preferences

---

package-lock.json
package.json
src/__snapshots__/storybook.test.ts.snap
src/components/RadioButtonGroup/index.tsx
src/components/RadioButtonGroup/utils.ts

enhancement #766 - RadioButtonGroup disabled state and infotip

---

package-lock.json
package.json
src/__snapshots__/storybook.test.ts.snap
src/components/Button/index.tsx
src/components/Modal/Modal.stories.tsx
src/components/Modal/Modal.tsx
src/components/Modal/ModalDrawer.tsx
src/components/Modal/ModalWrapper.tsx
src/components/Modal/index.tsx
src/components/Modal/utils.ts

enhancement #768 - [Modal] Add drawer mode

---

package-lock.json
package.json
src/components/EditableField/index.tsx
src/components/Tabs/index.tsx

* enhancement #770 - [Tabs] Add new tab functionality
* enhancement #771 - [EditableField] Add save icon
Closes #770 
Closes #771

enhancement #770, #771 -  Changes for dashboard tabs

---

src/components/ProgressBar/index.tsx

enhancement #773 - [Progress Bar] Add ability to pass in bar and container classes

---

package-lock.json
package.json
src/components/Tabs/index.tsx

enhancement #776 - Tabs limit

---

package-lock.json
package.json
src/components/Filters/FilterUnit/ValuesMultiSelect/utils.ts
src/components/Filters/FilterUnit/index.tsx

bugfix #778 - Filter key value notations reversed

---

package-lock.json
package.json
src/components/Input/index.tsx

enhancement #780 - [Input] Add min and max constraints

---

package-lock.json
package.json
src/components/EditableField/index.tsx

enhancement #782 - [EditableField] Max char limit

---

package-lock.json
package.json
src/components/EditableField/index.tsx

enhancement #784 - [EditableField] Throw error if input is empty 

---

package-lock.json
package.json
src/components/assets/styles/index.ts

chore #786 - Export color functions

---

package-lock.json
package.json
src/components/Modal/ModalDrawer.tsx
src/components/Modal/utils.ts

enhancement #788 - [Modal] Pass classes for overlay style

---

package-lock.json
package.json
src/components/Modal/ModalDrawer.tsx
src/components/Modal/utils.ts
src/components/Select/BaseSelect.tsx
src/components/Select/SingleSelect/types.ts
src/components/Table/types.ts
src/components/Table/utils.tsx

enhancement #790 - [Table] Add custom column type

---

package-lock.json
package.json
src/components/Table/types.ts
src/components/Table/utils.tsx

bugfix #792 - [Table] Allow event propagation to be configured for custom component cells

---

package-lock.json
package.json
src/__snapshots__/storybook.test.ts.snap
src/components/PriorityGrid/PriorityGrid.stories.tsx
src/components/PriorityGrid/PriorityGridAxisLabel.tsx
src/components/PriorityGrid/PriorityItem.tsx
src/components/PriorityGrid/PrioritySidebar.tsx
src/components/PriorityGrid/PrioritySidebarItem.tsx
src/components/PriorityGrid/index.tsx
src/components/PriorityGrid/styles.ts
src/components/PriorityGrid/utils.ts
src/components/Table/index.tsx
src/components/Table/types.ts
src/components/Table/utils.tsx

- enhancement #799 - [Priority Grid] Visual Updates
- enhancement #800 - [Table] UX Upgrades

enhancement #799, #800 - Upgrades for findings page

---

package-lock.json
package.json
src/components/Popover/index.tsx
src/components/PriorityGrid/PrioritySidebar.tsx
src/components/Select/BaseSelect.tsx
src/components/TreeSelect/index.tsx

bugfix #802, #804 - Fixes for findings page

---

package-lock.json
package.json
src/components/PriorityGrid/PriorityGridAxis.tsx
src/components/PriorityGrid/index.tsx

bugfix #809 - [Priority Grid] Fix axis label click

---

package-lock.json
package.json
src/__snapshots__/storybook.test.ts.snap
src/components/PriorityGrid/PriorityGrid.stories.tsx
src/components/PriorityGrid/PriorityItem.tsx
src/components/PriorityGrid/index.tsx

enhancement #811 - [Priority Grid] Loading state

---

package-lock.json
package.json
src/components/Table/index.tsx

enhancement #815 - [Table] Expose CellWithTooltip

---

package-lock.json
package.json

chore #817 - Fix vulnerabilities

---

package-lock.json
package.json
src/components/Tabs/index.tsx

enhancement #819 - Allow empty tab config if add tab callback provided

---

package-lock.json
package.json
src/components/Tabs/index.tsx

enhancement #823 - Custom add tab render

---

package-lock.json
package.json
src/components/Draggable/index.tsx
src/components/RadioButtonGroup/utils.ts

enhancement #828 - [Draggable] Add option to add separator after last item

---

package-lock.json
package.json
src/components/Modal/ModalDrawer.tsx

enhancement #832 - Drawer close callback

---

package-lock.json
package.json
src/components/Form/FormCheckbox/index.tsx
src/components/Form/FormChipInput/index.tsx
src/components/Form/FormCode/index.tsx
src/components/Form/FormDynamicKVInput/index.tsx
src/components/Form/FormInput/index.tsx
src/components/Form/FormMultiSelect/index.tsx
src/components/Form/FormMultipleChoice/index.tsx
src/components/Form/FormRadioButtonGroup/index.tsx
src/components/Form/FormSelect/index.tsx
src/components/Form/FormTagsSelect/index.tsx
src/components/Form/FormTimeInput/index.tsx
src/components/Form/FormTimezone/index.tsx
src/components/Form/FormToggle/index.tsx
src/components/Form/FormTree/index.tsx
src/components/Form/types.ts

enhancement #834 - [Form] Allow field label styles to be customized

---

package-lock.json
package.json
src/components/PageLoader/index.tsx

enhancement #836 - [Page Loader] Add generic option

---

package-lock.json
package.json
src/components/Breadcrumbs/index.tsx

enhancement #838 - [Breadcrumbs] Allow underline to be configurable

---

package-lock.json
package.json
src/__snapshots__/storybook.test.ts.snap
src/components/Button/utils.ts
src/components/Form/FieldError/index.tsx
src/components/Form/FormInput/index.tsx
src/components/Input/index.tsx
src/components/Modal/ModalWrapper.tsx
src/components/NotificationV2/Notification.tsx
src/components/NotificationV2/index.tsx
src/components/NotificationV2/utils.ts

enhancement #840 - [Form Input] Add customizability for form input and field error
enhancement #841 - [Notification] Allow popup to be customizable

enhancement #840, #841 - Updates for Tenable 

---

package-lock.json
package.json
src/components/PageLoader/index.tsx

enhancement #843 - [Page Loader] Allow loader to be customized

---

package-lock.json
package.json
src/components/PriorityGrid/utils.ts

bugfix #809 - [Priority Grid] Fix grid axis label click

---

package-lock.json
package.json
src/components/PageLoader/index.tsx

bugfix #852 - PageLoader background

---

package-lock.json
package.json
src/components/Input/index.tsx

bugfix #854 - TextArea enter key down should add new line

---

package-lock.json
package.json
src/components/Select/BaseSelect.tsx
src/components/Select/OptionChildren.tsx
src/components/Select/SingleSelect/Select.stories.tsx
src/components/Select/SingleSelect/types.ts
src/components/Select/fixtures/sample_options.ts

enhancement #860 - Select option icon with external url

---

package-lock.json
package.json
src/components/EditableField/index.tsx
src/components/PointerEventsNone/index.tsx
src/components/Tabs/index.tsx

enhancement #862 - Loading state for updating tabs

---

package-lock.json
package.json
src/components/Tabs/Tab.tsx

bugfix #864 - Inconsistent tab heights

---

package-lock.json
package.json
src/components/Tabs/Tab.tsx
src/components/Tabs/Tabs.stories.tsx

bugfix #866 - Show delete icon only if active tab

---

package-lock.json
package.json
src/components/Form/index.tsx

bugfix #868 - [Form] Prevent reset after submit

---

package-lock.json
package.json
src/components/Select/BaseSelect.tsx
src/components/Select/SingleSelect/types.ts

enhancement #882 - Single select on search

---

package-lock.json
package.json
src/components/Select/BaseSelect.tsx
src/components/Select/DropdownMenuSpinner.tsx
src/components/Select/MultiSelect/index.tsx
src/components/Select/SingleSelect/Select.stories.tsx
src/components/Select/SingleSelect/index.tsx
src/components/Select/SingleSelect/types.ts
src/components/Select/styles.ts

enhancement #884 - Select dropdown menu spinner

---

.github/workflows/codegen.yml
.github/workflows/node.js.yml
.github/workflows/npm-publish.yml
package-lock.json
package.json

Upgrade node version

---

package-lock.json
package.json
src/components/Select/BaseSelect.tsx

bugfix #889 - Select dropdown menu fixed to wrong component

---

package-lock.json
package.json
src/components/EditableField/index.tsx

bugfix #892 - [Editable Field] On submit error callback to reset field to original value

---

package-lock.json
package.json
src/components/PointerEventsNone/index.tsx
src/components/Tabs/Tab.tsx
src/components/Tabs/index.tsx

bugfix #894 - [Tabs] Fix pointer events none overriding close tab styles

---

package-lock.json
package.json

chore #898 - esbuild package error

---

src/components/Select/OptionChildren.tsx
src/components/Select/utils.ts

bugfix #911 - [Select] Fix truncated text tooltip not appearing in modal

---

package.json
src/components/Icon/index.tsx
src/components/Select/BaseSelect.tsx
src/components/Select/OptionChildren.tsx

enhancement #914 - Select option icon default src url

---

package-lock.json
package.json
src/components/Code/utils.ts

enhancement #918 - [Code] Update placeholder font

---

package-lock.json
package.json
src/components/Modal/ModalDrawer.tsx

enhancement #920 - [Modal] Pass onClose to overlay click

---

package-lock.json
package.json
src/components/Tabs/Tab.tsx
src/components/Tabs/index.tsx

enhancement #939 - Add customization tooltip to tabs on close

---

package-lock.json
package.json
src/components/Form/FormInput/index.tsx
src/components/Form/FormMultiSelect/index.tsx

enhancement #942 - [Form] Update form input and form multiselect to have configuration loading state

---

package-lock.json
package.json
src/components/Filters/BaseFilters.tsx
src/components/Filters/FilterPopover.tsx
src/components/Filters/FilterUnit/ValuesMultiSelect/ServerSide.tsx
src/components/Filters/FilterUnit/ValuesMultiSelect/utils.ts
src/components/Filters/FilterUnit/ValuesTagsSelect.tsx
src/components/Filters/FilterUnit/index.tsx
src/components/Filters/FiltersSummary.tsx
src/components/Filters/ServerSideFilters/index.tsx
src/components/Filters/ServerSideFilters/utils.ts
src/components/Filters/index.tsx
src/components/Filters/styles.ts
src/components/Filters/types.ts
src/components/Filters/utils.ts

enhancement #956 - [Filters] Enable filters to rendered outside of popover mode

---

package-lock.json
package.json
src/components/Slider/Slider.stories.tsx
src/components/Slider/index.tsx
src/components/Slider/styles.ts

enhancement #963 - Update slider component

---

package-lock.json
package.json
src/components/Tabs/ScrollableTabs.tsx
src/components/Tabs/Tab.tsx
src/components/Tabs/Tabs.stories.tsx
src/components/Tabs/index.tsx

enhancement #965 - Scrollable tabs

---

package-lock.json
package.json
src/components/Slider/index.tsx
src/components/Slider/styles.ts

enhancement #963 - Enable invert highlighted colors

---

package-lock.json
package.json
src/components/PageLoader/index.tsx

enhancement #969 - Make logo smaller
